RESPONSE_PATH: ./responses
PORT: 5000
LOG_PATH: ./logs
ALLOWED_MODULES: 
  - torch
  - builtins
  - nnsight
  - collections
  - operator
  - _operator
  - inspect
DISALLOWED_FUNCTIONS: []
MODEL_CONFIGURATIONS:
  - repo_id: EleutherAI/gpt-j-6b
    nnsight_class: nnsight.models.LanguageModel.LanguageModel
    kwargs: 
      device_map: auto
      
  - repo_id: mistralai/Mixtral-8x7B-v0.1
    nnsight_class: nnsight.models.LanguageModel.LanguageModel
    kwargs: 
      device_map: auto

  - repo_id: state-spaces/mamba-2.8b-slimpj
    nnsight_class: nnsight.models.Mamba.Mamba
    kwargs: 
      device: cuda
