RESPONSE_PATH: ./responses
PORT: 5550
LOG_PATH: ./logs
ALLOWED_MODULES: 
  - torch
  - builtins
  - nnsight
  - collections
  - operator
  - _operator
DISALLOWED_FUNCTIONS: []
MODEL_CONFIGURATIONS:
  - repo_id: EleutherAI/gpt-j-6b
  # - repo_id: meta-llama/Llama-2-70b-hf
    # max_memory:
    #   {
    #     0: "0GiB",
    #     1: "0GiB",
    #     2: "0GiB",
    #     3: "0GiB",
    #     4: "86GiB",
    #     5: "86GiB",
    #     6: "86GiB",
    #     7: "86GiB",
    #   }
