version: '3'
services:

  rabbitmq:
    image: rabbitmq:3.11.28
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
        
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass 

  api:
    image: api:latest
    ports:
      - 5000:80
    environment:
      RMQ_URL: amqp://guest:guest@rabbitmq:5672/
      MONGO_URL: mongodb://user:pass@mongodb:27017/celery_result_backend 
      WORKERS: 12

  request:
    image: request:latest
    environment:
      API_URL: https://ndif.dev
      RMQ_URL: amqp://guest:guest@rabbitmq:5672/
      MONGO_URL: mongodb://user:pass@mongodb:27017/celery_result_backend

  model-gpt2-xl:
    image: model:latest
    environment:
      API_URL: https://ndif.dev
      RMQ_URL: amqp://guest:guest@rabbitmq:5672/
      MONGO_URL: mongodb://user:pass@mongodb:27017/celery_result_backend 
      REPO_ID: gpt2-xl
      CUDA_LAUNCH_BLOCKING: 1
    volumes:
      - /disk/u/jfiottok/.cache/huggingface/hub/:/home/celery/.cache/huggingface/hub
    deploy:
      replicas: 2
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 8
              capabilities: [gpu]

  model-gptj:
    image: model:latest
    environment:
      API_URL: https://ndif.dev
      RMQ_URL: amqp://guest:guest@rabbitmq:5672/
      MONGO_URL: mongodb://user:pass@mongodb:27017/celery_result_backend 
      REPO_ID: EleutherAI/gpt-j-6b
      CUDA_LAUNCH_BLOCKING: 1
    volumes:
      - /disk/u/jfiottok/.cache/huggingface/hub/:/home/celery/.cache/huggingface/hub
    deploy:
      replicas: 3
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 8
              capabilities: [gpu]













