channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - git
  - pip:
    - pip
    - setuptools
    - git+https://github.com/ndif-team/nnsight@0.3
    - ray[serve]
    - prometheus-client
    - opencensus
    - aiohttp_cors
    # Database
    - pymongo