version: '3'
services:

  dev-mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - 27016:27017

  dev-api:
    image: api:latest
    ports:
      - 5001:80
    environment:
      MONGO_URL: mongodb://user:pass@nagoya.research.khoury.northeastern.edu:27017/service
      WORKERS: 12

  dev-ray-head:
    image: ray_head:latest
    ports:
      - 8265:8265
      - 6379:6379
