channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - git
  - pip:
    - pip
    - setuptools
    - git+https://github.com/ndif-team/nnsight@dev
    - ray[serve]
    # Database
    - minio