channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip

  - pip:
    - pip
    - setuptools
    - nnsight
    - ray[serve]
    # Telemetry
    - prometheus_client
    - python-logging-loki
    # Database
    - pymongo
