channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip

  - pip:
    - pip
    - setuptools
    - fastapi==0.108.0
    - fastapi-socketio
    - socketio
    - uvicorn[standard]==0.24.0
    - gunicorn
    - eventlet
    - pymongo
    - celery
    - aio_pika
    - requests
    - torch
    - nnsight==0.2.0.dev2
    - firebase-admin