channels:
  - conda-forge
dependencies:
  - python=3.10
  - git 
  - pip

  - pip:
    - pip
    - setuptools
    - pymongo
    - celery
    - requests
    - torch
    - git+https://github.com/ndif-team/nnsight.git@0.3
    - numpy