version: '3'
services:

  rabbitmq:
    image: rabbitmq:3.11.28
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - 5673:5672

  minio:
    image: minio/minio:latest
    ports:
      - 27018:9000

  ray-head:
    image: ray_head:latest
    shm_size: '15gb'
    volumes:
      - /disk/u/jfiottok/.cache/huggingface/hub/:/root/.cache/huggingface/hub
      - /disk/u/jfiottok/wd/ndif/compose/prod/service_config.yml:/src/ray/config/service_config.yml
      - /disk/u/jfiottok/wd/ndif/compose/prod/ray_config.yml:/src/ray/config/ray_config.yml
      - /disk/u/jfiottok/wd/ndif/compose/prod/ray-head-start.sh:/start.sh
    
    ports:
      - 6380:6379
      - 9998:10001
      - 8266:8265
    deploy:
      replicas: 1
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 8
              capabilities: [ gpu ]

  api:
    image: api:latest
    ports:
      - 5001:80
    environment:
      OBJECT_STORE_URL: nagoya.research.khoury.northeastern.edu:27018
      RMQ_URL: amqp://guest:guest@nagoya.research.khoury.northeastern.edu:5673/
      WORKERS: 12
      RAY_ADDRESS: ray://nagoya.research.khoury.northeastern.edu:9998
      FIREBASE_CREDS_PATH: /src/creds.json
