name: engine
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - git+https://github.com/davidbau/baukit.git
    - git+https://github.com/huggingface/transformers.git
    - protobuf==3.13.0
    - accelerate
    - tokenizers
    - openapi_schema_pydantic
    - pydantic
    - shortuuid
    - flask
